### PR TITLE
Feature: windows authentication support

### PR DESCRIPTION
**Pull request by nilleb**
The Jenkins server might be reverse-proxied by an Apache server performing the authentication of the users.

This configuration helps the transparent authentication of the users in an Active Directory domain. This solution outsports Jenkins LDAP/Active Directory plugins in terms of performance.

Nevertheless, the plugin needs to provide the credentials of the logged user. Otherwise, the connection will fail with a HTTP 401 (the so called 401-stimulation).

### CODE REVIEW

**Comment by nilleb** [comment]
The described environment eliminates the need to save the password of the user in a n-th extra configuration file, since the kerberos ticket of the currently logged user is being used to authentify.

The proposed patch sends the credentials (kerberos ticket/ntlm credentials) of the currently logged user to the server, if it asks for them by means of the HTTP 401 stimulation.

**Comment by tomkuijsten** [comment]
Thanks for the pull request, I'll review it this week.

**Comment by tomkuijsten** [comment]
Nice addition, I don't have this setup myself. When I release this version to visualstudioextensions, are you willing to test it?

**Comment by nilleb** [comment]
Yes, I am!

Il giorno lun 15 giu 2015 10:13 Tom Kuijsten <notifications@github.com> ha
scritto:

**Comment by tomkuijsten** [comment]
It's included in version 1.0.0.4 which was released yesterday, I created an issue #38 for it.

**Pull request merged**
